#!/bin/bash

# BUILD
xsd2cpp fixedTest.xsd . && ./autogen.sh &&  make install
if [ $? -ne 0 ]; then
  echo "   failed to build in dir: `pwd`"
  exit 1
fi

# TEST
run=./build/bin/fixedTestrun

$run -r t1.xml
if [ $? -ne 0 ]; then
  echo "   test failed in dir: `pwd`"
  exit 1  
fi

$run -r t3.xml
if [ $? -ne 0 ]; then
  echo "   test failed in dir: `pwd`"
  exit 1  
fi

$run -r t2.xml
if [ $? -eq 0 ]; then
  echo "   negative test failed on t2.xml in dir: `pwd`"
  exit 1  
fi
