#!/bin/bash

# BUILD
xsd2cpp xsiTest.xsd . && ./autogen.sh &&  make install
if [ $? -ne 0 ]; then
  echo "   failed to build in dir: `pwd`"
  exit 1
fi

# TEST
run=./build/bin/xsiTestrun
$run -w && $run -v valid.xml && $run -v valid2.xml
if [ $? -ne 0 ]; then
  echo "   test failed in dir: `pwd`"
  exit 1  
fi

